# Generated by Django 5.1.7 on 2025-03-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='medicine',
            name='active_ingredient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='usage_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinetransaction',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
