# Generated by Django 5.1.7 on 2025-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_medicine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicinetransaction',
            name='transaction_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
