# Generated by Django 5.1.7 on 2025-04-02 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_medicinetransaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinetransaction',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='medicinetransaction',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicinetransaction',
            name='quantity',
        ),
        migrations.CreateModel(
            name='MedicineTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.medicine')),
                ('medicine_transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.medicinetransaction')),
            ],
        ),
    ]
