# Generated by Django 5.1.7 on 2025-04-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_medicinetransactiondetail_medicine_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinetransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinetransactiondetail',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_detail_medicine', to='pharmacy.medicine'),
        ),
        migrations.AlterField(
            model_name='medicinetransactiondetail',
            name='medicine_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_detail', to='pharmacy.medicinetransaction'),
        ),
    ]
