# Generated by Django 5.1.7 on 2025-04-04 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_medicinetransaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinetransactiondetail',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medicine', to='pharmacy.medicine'),
        ),
    ]
