# Generated by Django 5.1.7 on 2025-04-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_medicinetransactiondetail_medicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'medicine', 'verbose_name_plural': 'medicines'},
        ),
        migrations.AlterModelOptions(
            name='medicinetransaction',
            options={'ordering': ['-date'], 'verbose_name': 'medicine transaction', 'verbose_name_plural': 'medicine transactions'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name']},
        ),
    ]
