# Generated by Django 5.1.7 on 2025-03-22 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_behavior_pattern_animal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='arrival_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 22, 12, 56, 22, 564602, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='animal',
            name='surrender_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
