# Generated by Django 5.1.7 on 2025-03-24 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_animalbreed_animalspecies_alter_animal_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalbreed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.animalspecies'),
        ),
    ]
