# Generated by Django 5.1.7 on 2025-03-24 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_alter_animalbreed_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
