# Generated by Django 5.1.7 on 2025-03-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0010_animaltransaction'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalshelter',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.warehouse'),
        ),
        migrations.AddField(
            model_name='animaltransaction',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='animal', to='animal.animal'),
        ),
        migrations.AddField(
            model_name='animaltransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_animal_transaction_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animaltransaction',
            name='to_shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_shelter', to='animal.animalshelter'),
        ),
        migrations.AddField(
            model_name='animaltransaction',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='updated_animal_transaction_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
