# Generated by Django 5.1.7 on 2025-03-31 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0011_animalshelter_warehouse_animaltransaction_animal_and_more'),
        ('pharmacy', '0002_remove_medicine_warehouse_medicine_active_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaltransaction',
            name='from_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='from_shelter', to='animal.animalshelter'),
        ),
        migrations.AlterField(
            model_name='animalshelter',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='warehouse_for_shelter', to='pharmacy.warehouse'),
        ),
        migrations.AlterField(
            model_name='animaltransaction',
            name='to_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_shelter', to='animal.animalshelter'),
        ),
    ]
