# Generated by Django 5.1.7 on 2025-04-08 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0013_examination_medication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['id_number', 'arrival_date'], 'verbose_name': 'animal', 'verbose_name_plural': 'animals'},
        ),
        migrations.AlterModelOptions(
            name='animalbreed',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='animalshelter',
            options={'ordering': ['name'], 'verbose_name': 'animal shelter', 'verbose_name_plural': 'animal shelters'},
        ),
        migrations.AlterModelOptions(
            name='animalspecies',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='animaltransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'animal transaction', 'verbose_name_plural': 'animal transactions'},
        ),
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['-examination_date', 'animal'], 'verbose_name': 'examination', 'verbose_name_plural': 'examinations'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-medication_date', 'name'], 'verbose_name': 'medication', 'verbose_name_plural': 'medications'},
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medicine',
        ),
        migrations.CreateModel(
            name='MedicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_detail', to='animal.medication')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='animal_medication_detail', to='animal.medication')),
            ],
            options={
                'verbose_name': 'medication detail',
                'verbose_name_plural': 'medication details',
                'ordering': ['medication', 'id'],
            },
        ),
    ]
