# Generated by Django 5.1.7 on 2025-04-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0014_alter_animal_options_alter_animalbreed_options_and_more'),
        ('pharmacy', '0009_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdetail',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='animal_medication_detail', to='pharmacy.medicine'),
        ),
    ]
