# Generated by Django 5.1.7 on 2025-04-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0016_medicationdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
