# Generated by Django 5.1.7 on 2025-04-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0017_alter_medicationdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdetail',
            name='created_at',
            field=models.DateTimeField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='medicationdetail',
            name='updated_at',
            field=models.DateTimeField(default='2023-01-01'),
        ),
    ]
