# Generated by Django 5.1.7 on 2025-04-11 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0018_alter_medicationdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdetail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicationdetail',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
