# Generated by Django 5.1.7 on 2025-04-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0019_alter_medicationdetail_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicationdetail',
            name='updated_at',
        ),
    ]
